### ISSUE TITLE
ImportError: cannot import name 'syslog_priorities'

### ISSUE THREAD

**Issue by aaronfay** [mosquito/cysystemd#17]
It seems like a file is missing in `systemd@0.16.1`:

```
(awslogs-sd) [root@a0d03d]# AWS_DEFAULT_REGION=us-east-1 /opt/awslogs-sd/bin/awslogs-sd /etc/awslogs-sd.conf
Traceback (most recent call last):
  File "/opt/awslogs-sd/bin/awslogs-sd", line 7, in <module>
    from awslogs_sd.awslogs_sd import main
  File "/opt/awslogs-sd/lib64/python3.6/site-packages/awslogs_sd/awslogs_sd.py", line 22, in <module>
    from systemd import journal
  File "/opt/awslogs-sd/lib64/python3.6/site-packages/systemd/journal.py", line 6, in <module>
    from ._journal import syslog_priorities, send
ImportError: cannot import name 'syslog_priorities'
```

When I look at the contents of that installed module I don't see a `_journal.py(x)` file:

```
(awslogs-sd) [root@a0d03d]# ll /opt/awslogs-sd/lib64/python3.6/site-packages/systemd/
total 1496
-rwxr-xr-x 1 root root   60464 Jun 14 19:27 _daemon.cpython-36m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root    2059 Dec 15  2017 daemon.py
-rwxr-xr-x 1 root root   42512 Jun 14 19:27 id128.cpython-36m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root     471 Mar  1  2018 __init__.py
-rwxr-xr-x 1 root root   34144 Jun 14 19:27 _journal.cpython-36m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root    4522 Dec 15  2017 journal.py
-rwxr-xr-x 1 root root   52848 Jun 14 19:27 login.cpython-36m-x86_64-linux-gnu.so
drwxr-xr-x 2 root root      96 Jun 14 19:27 __pycache__
-rwxr-xr-x 1 root root  112064 Jun 14 19:27 _reader.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x 1 root root 1203496 Jun 14 19:27 reader.cpython-36m-x86_64-linux-gnu.so
drwxr-xr-x 3 root root      91 Jun 14 19:27 test
```

Am I missing something here?

**Comment by aaronfay** [comment]
This morning I'm unable to recreate the issue. Closing for now.
